<a href="https://colab.research.google.com/github/Coder3338/deep-learning/blob/main/EXP_1_Advanced_DL_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from __future__ import print_function
import tensorflow as tf


In [9]:

import tensorflow as tf

primes = tf.constant([2,4,6,8,10,12], dtype=tf.int32)
print("primes:", primes)

ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)

just_beyond_primes = tf.add(primes, ones)
print("just_beyond_primes:", just_beyond_primes)

twos = tf.constant([4,4,4,4,4,4], dtype=tf.int32)
primes_doubled = primes + twos
print("primes_doubled:", primes_doubled)

some_matrix = tf.constant([[2,3,4], [1,2,3],[2,3,4]], dtype=tf.int32)
print(some_matrix)

print("\nvalue of some_matrix is:\n", some_matrix.numpy())


primes: tf.Tensor([ 2  4  6  8 10 12], shape=(6,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)
just_beyond_primes: tf.Tensor([ 3  5  7  9 11 13], shape=(6,), dtype=int32)
primes_doubled: tf.Tensor([ 6  8 10 12 14 16], shape=(6,), dtype=int32)
tf.Tensor(
[[2 3 4]
 [1 2 3]
 [2 3 4]], shape=(3, 3), dtype=int32)

value of some_matrix is:
 [[2 3 4]
 [1 2 3]
 [2 3 4]]
